// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27QvAyGjCl9Z-ZywG2YeqMmcX-lRXiOE',
    appId: '1:288808059101:web:5c2ff099fe354a76855b34',
    messagingSenderId: '288808059101',
    projectId: 'fbtest-ec5ca',
    authDomain: 'fbtest-ec5ca.firebaseapp.com',
    databaseURL: 'https://fbtest-ec5ca.firebaseio.com',
    storageBucket: 'fbtest-ec5ca.appspot.com',
    measurementId: 'G-8N23FF92DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5p1SLmsUrwPZ116IKXYYHo1KD9xZHroo',
    appId: '1:288808059101:android:20bfc76d4ae4a9a1855b34',
    messagingSenderId: '288808059101',
    projectId: 'fbtest-ec5ca',
    databaseURL: 'https://fbtest-ec5ca.firebaseio.com',
    storageBucket: 'fbtest-ec5ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDQ9Y65xsH6tPwX4PlAVjRKtBC4r5PBs',
    appId: '1:288808059101:ios:5c3832bf0dc2411e855b34',
    messagingSenderId: '288808059101',
    projectId: 'fbtest-ec5ca',
    databaseURL: 'https://fbtest-ec5ca.firebaseio.com',
    storageBucket: 'fbtest-ec5ca.appspot.com',
    androidClientId: '288808059101-8i19ae9657893bd6ukur75l67ds1rehe.apps.googleusercontent.com',
    iosClientId: '288808059101-5j1pbk0i2slmuet5pnlk4l0db0mh30m8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTraining',
  );
}
